---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
          wrap-iife:
            enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "gulp.config.js"
- "gulpfile.js"
- "karma.conf.js"
- "src/client/app/events/list/eventlist.controller.spec.js"
- "src/client/app/events/view/isattendingevent.filter.spec.js"
- "src/client/app/events/list/iscurrentevent.filter.spec.js"
- "src/client/app/events/create/createevent.controller.spec.js"
- "src/client/app/events/view/eventview.controller.spec.js"
- "src/client/app/users/list/userlist.controller.spec.js"
- "src/client/app/users/view/userview.controller.spec.js"
- "src/client/app/users/create/user.create.controller.spec.js"
- "src/client/app/groups/list/grouplist.controller.spec.js"
- "src/client/app/groups/view/groupview.controller.spec.js"
- "src/client/app/groups/groupicon.service.spec.js"
- "src/client/app/groups/group.service.spec.js"
- "src/client/app/common/logger/logger.service.spec.js"
- "src/client/app/security/security.controller.spec.js"
- "src/client/app/location/list/locationlist.controller.spec.js"
- "src/client/app/location/view/locationview.controller.spec.js"
- "src/client/app/location/location.service.spec.js"
- "src/client/app/users/user.service.spec.js"
- "src/client/app/events/event.service.spec.js"
- "src/client/test-helpers/event-managing-event.mock-services.js"
- "src/client/test-helpers/mock-data.js"
- "src/client/test-helpers/bind-polyfill.js"
- "src/client/test-helpers/group-mock-data.js"
- "src/client/test-helpers/user-mock-data.js"
