---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
          wrap-iife:
            enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "gulp.config.js"
- "gulpfile.js"
- "karma.conf.js"
- "src/client/app/events/list/eventlist.controller.spec.js"
- "src/client/app/events/view/isattendingevent.filter.spec.js"
- "src/client/app/groups/list/grouplist.controller.spec.js"
- "src/client/app/users/list/userlist.controller.spec.js"
- "src/client/app/groups/view/groupview.controller.spec.js"
- "src/client/app/groups/groupicon.service.spec.js"
- "src/client/test-helpers/mock-data.js"
- "src/client/test-helpers/bind-polyfill.js"
