language: node_js
node_js:
  - stable
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g istanbul

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat report/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

addons:
    code_climate:
        repo_token: cc7753cc1d1d53cda2e7bd7647011163689e73e7d616eec6b22365456b102b45
